language: python
matrix:
  include:
    # Python 3.5
    - python: 3.5
      env: TOXENV=py35

    # pypy3
    - python: pypy3
      env: TOXENV=pypy3

  allow_failures:
    - python: pypy3

install:
  - pip install -r requirements/test.txt
  - pip install -r requirements/docs.txt

script:
  - py.test --cov=schematics_xml
  - pylint schematics_xml
  - cd docs && make clean html

after_success:
  - bash <(curl -s https://codecov.io/bash)
